version: '3'
services:
    client:
        image: "maroofshaikh09/multi-client-10-14"
        hostname: client
        mem_limit: 128m
    server:
        image: "maroofshaikh09/multi-server-10-14"
        hostname: api
        mem_limit: 128m
        environment:
          - REDIS_HOST= $REDIS_HOST
          - REDIS_PORT= $REDIS_PORT
          - PGUSER= $PGUSER
          - PGHOST= $PGHOST
          - PGDATABASE= $PGDATABASE
          - PGPASSWORD= $PASSWORD
          - PGPORT= $PGPORT
    worker:
        image: "maroofshaikh09/multi-worker-10-14"
        hostname: worker
        mem_limit: 128m
        environment: 
          - REDIS_HOST= $REDIS_HOST
          - REDIS_PORT= $ REDIS_PORT
    nginx:
        image: "maroofshaikh09/multi-nginx-10-14",
        hostname: nginx
        mem_limit: 128m
        ports:
            - "80:80"
