name: multi-docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: before install
      run: |
        docker build -t maroofshaikh09/multi-client -f ./client/Dockerfile.dev ./client
        docker build -t maroofshaikh09/multi-nginx -f ./nginx/Dockerfile.dev ./nginx
        docker build -t maroofshaikh09/multi-server -f ./server/Dockerfile.dev ./server
        docker build -t maroofshaikh09/multi-worker -f ./worker/Dockerfile.dev ./worker
    - name: script
      run: |
        docker run -e CI=true maroofshaikh09/multi-client npm test
        docker run -e CI=true maroofshaikh09/multi-nginx npm test
        docker run -e CI=true maroofshaikh09/multi-server npm test
        docker run -e CI=true maroofshaikh09/multi-worker npm test
    - name: after install
      run: |
        docker push maroofshaikh09/multi-client 
        docker push maroofshaikh09/multi-nginx
        docker push maroofshaikh09/multi-server
        docker push maroofshaikh09/multi-worker
 
